language: cpp
compiler:
    -clang
before_install:
    - sudo apt-get update
    - sudo apt-get install cmake flex bison
before_script:
    - pwd
    - which sh
script: "./.travis.build"
branches:
    only:
        - master
notifications:
    recipients:
        - chirag.sakhuja@utexas.edu
    email:
        on_success: change
        on_failure: always
